server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos-server-addr:localhost:8848}
        namespace: ${nacos-namespace:}
        group: DEFAULT_GROUP
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database-address}:3306/class_times_record?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: class_times_record
    password: 8BCnbZjTT8ZxmBj6
  threads:
    virtual:
      enabled: true

crypto:
  sm2:
    private-key: 00b3b8e61213bbd5e7d001e0cd4e33015efc04ae68ae61f2a36da55d92903cb0eb

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath:com/shiroko/mapper/**/*.xml
  type-aliases-package: com.shiroko.repository.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: isDeleted
      logic-not-delete-value: 0
      logic-delete-value: 1
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL

jwt:
  secret: class-times-record-secret-key-2024
  expiration: 86400000

uni-app:
  wx:
    app-id: wx8b6acdafc6f87e0c
    secret: 76104b412a0f8432368758dad8d5bb69
