server:
  port: 9999
  address: 121.196.229.10
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    com.shiroko: DEBUG
