spring:
  application:
    name: cr-admin-service
  config:
    import:
      - optional:nacos:cr-admin-service.yaml?group=DEFAULT_GROUP&refresh=true
      - optional:nacos:common-db.yaml?group=DEFAULT_GROUP&refresh=true
      - optional:nacos:common-sentinel.yaml?group=DEFAULT_GROUP&refresh=true
      - optional:nacos:logback-spring.xml?group=DEFAULT_GROUP&refresh=true
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:https://nacos.kurimula-airi.top}
      discovery:
        namespace: ${NACOS_NAMESPACE:course-record}
        group: DEFAULT_GROUP
      config:
        namespace: ${NACOS_NAMESPACE:course-record}
        group: DEFAULT_GROUP
        file-extension: yaml

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml,classpath*:com/shiroko/mapper/*.xml